package Bomber;

public enum BombermanType {
    PLAYER, WALL, BRICK, BOMB, FIRE,
    SPEED_ITEM, BOMB_ITEM, FLAME_ITEM,
    PORTAL, BRICK_BREAK, FLAME_PASS_ITEM,
    GRASS, CORAL, GRASS_BREAK, BALLOOM_E,
    ONEAL_E, CORAL_BREAK, WALL_BOMB
}
